#!/usr/bin/env zsh

source "$HOME/dotfiles/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/dotfiles/.config/sketchybar/plugins"
FONT_FACE="JetBrainsMono Nerd Font"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# Move to colors and also change the color

sketchybar --bar color=0x66494d64 \
                 border_color=$PEACH \
                 border_width=0 \
                 shadow=off \
                 sticky=on \
                 height=32 \
                 y_offset=6 \
                 margin=6 \
                 padding_right=20 \
                 padding_left=20 \
                 blur_radius=64 \
                 corner_radius=10 \
                 display=main

sketchybar --default icon.font="$FONT_FACE:Regular:20.0" \
                     icon.color=$GREEN \
                     icon.padding_left=10 \
                     icon.padding_right=10 \
                     label.color=$TEXT \
                     label.font="$FONT_FACE:Regular:16.0" \
                     label.padding_right=10 \
                     background.height=32 \
                     background.corner_radius=16 \
                     background.padding_left=10 \
                     background.padding_right=10


sketchybar --add item clock right \
    --set clock \
    background.border_color=$BLUE \
    background.border_width=1 \
    background.padding_left=0 \
    icon=󰃰 \
    icon.color=$YELLOW \
    icon.padding_left=40 \
    background.color=$SURFACE0 \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh" \

sketchybar --add item weather.icon right \
           --set weather.icon \
           icon="" \
           icon.color=$SAPPHIRE \
           icon.y_offset=5 \
           icon.font="$FONT_FACE:Regular:15.0" \
           background.padding_right=-50

sketchybar --add item weather.temp right \
           --set weather.temp \
           label.padding_left=0 \
	         label.padding_right=0 \
           label.align=right \
	         background.padding_right=-37 \
	         background.padding_left=0 \
           label.font="$FONT_FACE:Regular:10.0" \
           y_offset=-6 \
           script="$PLUGIN_DIR/weather.sh"


sketchybar --add item memory right \
           --set memory \
           icon= \
           icon.padding_left=190 \
           icon.color=$RED \
           background.color=$SURFACE0 \
           background.border_color=$BLUE \
           background.border_width=1 \
           background.padding_right=7 \
           update_freq=15 \
           label="$(memory_pressure | grep "System-wide memory free percentage:" | awk '{ printf("%02.0f\n", 100-$5"%") }')%"

sketchybar --add item cpu right \
           --set cpu \
           icon= \
           icon.color=$BLUE \
           background.padding_right=-200 \
           update_freq=4 \
           script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item tempcpu right \
           --set tempcpu \
           background.padding_right=-20 \
           icon="" \
           icon.color=$PEACH \
           update_freq=10 \
           script="$PLUGIN_DIR/temperature.sh"

sketchybar --add item wifi right \
           --set wifi \
           background.color=$SURFACE0 \
           background.border_color=$BLUE \
           background.border_width=1 \
           icon=  \
           icon.color=$BLUE \
           update_freq=15 \
           script="$PLUGIN_DIR/wifi.sh"

sketchybar --add item front_app left \
           --set front_app \
           background.color=$SURFACE0 \
           background.border_color=$BLUE \
           background.border_width=1 \
           icon.background.drawing=on \
           label.padding_right=20 \
           display=active \
           script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

sketchybar --add event spotify_change $SPOTIFY_EVENT \
           --add item spotify left \
           --set spotify \
           icon= \
           icon.y_offset=1 \
           background.border_color=$BLUE \
           background.border_width=1 \
           background.color=$SURFACE0 \
           label.drawing=off \
           label.padding_left=3 \
           script="$PLUGIN_DIR/spotify.sh" \
           --subscribe spotify spotify_change mouse.clicked

sketchybar --add item battery right \
           --set battery \
           background.color=$SURFACE0 \
           background.border_color=$BLUE \
           background.border_width=1 \
           update_freq=15 \
           script="$PLUGIN_DIR/battery.sh"

sketchybar --hotload on
sketchybar --update
