#!/usr/bin/env zsh

source "$HOME/dotfiles/.config/sketchybar/colors.sh"

PLUGIN_DIR="$HOME/dotfiles/.config/sketchybar/plugins"
FONT_FACE="JetBrainsMono Nerd Font"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# Move to colors and also change the color

sketchybar --bar color=0x66494d64 \
                 border_color=$PEACH \
                 border_width=0 \
                 shadow=off \
                 sticky=on \
                 height=32 \
                 y_offset=6 \
                 margin=6 \
                 padding_right=20 \
                 padding_left=20 \
                 blur_radius=64 \
                 corner_radius=10 \
                 display=main

sketchybar --default icon.font="$FONT_FACE:Regular:20.0" \
                     icon.color=$ICON_COLOR \
                     icon.padding_left=10 \
                     icon.padding_right=10 \
                     label.color=$LABEL_COLOR \
                     label.font="$FONT_FACE:Regular:16.0" \
                     label.padding_right=10 \
                     background.height=30 \
                     background.corner_radius=16 \
                     background.padding_left=10 \
                     background.padding_right=10


sketchybar --add item clock right \
    --set clock \
    background.border_color=$BLUE \
    background.border_width=1 \
    icon=󰃰 \
    background.color=$BLUE \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh" \

sketchybar --add event spotify_change $SPOTIFY_EVENT \
           --add item spotify right \
           --set spotify \
           icon= \
           icon.y_offset=1 \
           background.color=$RED \
           label.drawing=off \
           label.padding_left=3 \
           script="$PLUGIN_DIR/spotify.sh" \
           --subscribe spotify spotify_change mouse.clicked

sketchybar --add item memory right \
           --set memory \
           icon= \
           background.color=$BLUE \
           update_freq=15 \
           label="$(memory_pressure | grep "System-wide memory free percentage:" | awk '{ printf("%02.0f\n", 100-$5"%") }')%"

sketchybar --add item cpu right \
           --set cpu \
           icon= \
           background.color=$YELLOW \
           update_freq=4 \
           script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item tempcpu right \
           --set tempcpu \
           background.color=$YELLOW \
           icon="" \
           update_freq=10 \
           script="$PLUGIN_DIR/temperature.sh"

sketchybar --add item front_app left \
           --set front_app \
           background.color=$BLUE \
           icon.background.drawing=on \
           display=active \
           script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

sketchybar --hotload on
sketchybar --update
