import = [
  "~/.config/alacritty/themes/themes/zenburn.toml"
]

[shell]
program = "/bin/zsh"
args = ["--login"]

[cursor]
style = "Block"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 16.0

[window]
option_as_alt = "OnlyLeft"

