require("vim._extui").enable({ enable = true, msg = { target = "msg" } })
require("config")
require("current-theme")

vim.lsp.enable("postgres_lsp")
vim.lsp.enable("lua_ls")
vim.lsp.enable("clangd")
vim.lsp.enable("pyrefly")
vim.lsp.enable("gopls")
vim.lsp.enable("jsonls")
vim.lsp.enable("yamlls")
vim.lsp.enable("zls")
vim.lsp.enable("marksman")
vim.lsp.enable("asm_lsp")
vim.lsp.enable("glsl_analyzer")
vim.lsp.enable("nixd")
